
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class KaseyaVSA9Agent(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class KaseyaVSA9Asset(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class KaseyaVSA9MachineGroup(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class KaseyaVSA9Organization(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class KaseyaVSA9User(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
