
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class SuseManagerAsset(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SuseManagerAssetGroup(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SuseManagerExposure(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SuseManagerFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SuseManagerIdentity(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SuseManagerOrganization(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SuseManagerSoftware(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SuseManagerSoftwareInstallation(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
