
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class ProxmoxPVEGroup(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ProxmoxPVENode(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ProxmoxPVEStorage(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ProxmoxPVEUser(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ProxmoxPVEVM(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
