
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class SysdigSecureAwsAccount(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SysdigSecureCloudProvider(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SysdigSecureFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SysdigSecureHost(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SysdigSecureImage(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SysdigSecureKubeCluster(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SysdigSecureKubeNode(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SysdigSecureKubeWorkload(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SysdigSecureVulnerability(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
