
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""

from typing import Any, Optional, TypedDict  # noqa: F401

Settings = TypedDict('Settings', {
    'auth_type': str,
    'organization': Optional[str],
    'url': str,
    'api_token': str,
    'verify_tls': bool,
    'severity': str,
    'types': Optional[list],
    'look_back_days': int,
})
