
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class GophishPlatformCampaign(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class GophishPlatformFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class GophishPlatformGroup(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class GophishPlatformTemplate(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class GophishPlatformUser(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
