"""
Any code that is shared between the functions in this connector
should be placed here, so that it can be reused by all functions.
"""

import hashlib
import ipaddress
import json
from logging import Logger
from datetime import datetime, timedelta, timezone
from r7_surcom_api import HttpSession

from .sc_settings import Settings

# Maximum page size for Mimecast API pagination
PAGE_SIZE = 100

BASE_URL = "https://api.services.mimecast.com"

# Threat id are generated by grouping key values.
THREAT_PROPERTIES = [
    "email",
    "status",
    "spamCount",
    "malwareCount",
    "phishingCount",
    "suspiciousCount",
    "unwantedCount",
    "untrustworthyCount",
    "totalCount",
]


class MimecastClient:
    """Client for interacting with Mimecast APIs."""

    def __init__(self, user_log: Logger, settings: Settings):
        # Expose the logger to the client
        self.logger = user_log

        # Expose the Connector Settings to the client
        self.settings = settings

        # Use the standard Mimecast API base URL
        self.base_url = BASE_URL

        # Load and validate lookback_days from settings, with a safe default
        raw_lookback = self.settings.get("lookback_days")
        default_lookback = 30
        if raw_lookback is None:
            lookback_days = default_lookback
        else:
            try:
                lookback_days = int(raw_lookback)
            except (TypeError, ValueError):
                self.logger.warning(
                    "Invalid 'lookback_days' value '%s'; defaulting to %d days.",
                    raw_lookback,
                    default_lookback,
                )
                lookback_days = default_lookback
        if not 1 <= lookback_days <= 90:
            self.logger.warning(
                "'lookback_days' value %d is out of range (1 to 90); defaulting to %d days.",
                lookback_days,
                default_lookback,
            )
            lookback_days = default_lookback
        self.lookback_days = lookback_days

        # Setup a Session using the Surcom HttpSession class
        self.session = HttpSession()

        # Setup authentication
        self._setup_authentication()

    def _setup_authentication(self):
        """Setup OAuth authentication for Mimecast API requests."""
        # Get OAuth credentials from settings
        client_id = self.settings.get("client_id")
        client_secret = self.settings.get("client_secret")

        if not client_id or not client_secret:
            raise ValueError("client_id and client_secret are required")

        # Set up required Mimecast headers first
        self.session.headers.update({"Content-Type": "application/json"})

        # Get OAuth access token
        self.access_token = self._get_oauth_token(client_id, client_secret)
        # Set up headers for Mimecast API authentication with OAuth token
        self.session.headers.update({"Authorization": f"Bearer {self.access_token}"})

    def _get_oauth_token(self, client_id, client_secret):
        """
        Obtain OAuth access token using Mimecast authentication.

        Args:
            client_id (str): OAuth client ID
            client_secret (str): OAuth client secret

        Returns:
            str: Access token for API requests

        Raises:
            Exception: If token request fails
        """
        token_url = f"{self.base_url}/oauth/token"

        # Prepare OAuth2 client credentials request data
        token_data = {
            "grant_type": "client_credentials",
            "client_id": client_id,
            "client_secret": client_secret,
        }

        # Set proper headers for OAuth token request
        oauth_headers = {"Content-Type": "application/x-www-form-urlencoded"}

        # Make token request with form data and proper headers
        response = self.session.post(token_url, data=token_data, headers=oauth_headers)

        response.raise_for_status()

        token_response = response.json()

        # Extract access token from OAuth2 response structure
        access_token = token_response.get("access_token")
        if not access_token:
            raise ValueError("No access token received from OAuth response")

        return access_token

    @staticmethod
    def hash(item: dict, keys) -> str:
        """
        Generate a hash from the values of the specified keys in the item
        """
        m = hashlib.sha256()
        for k in sorted(keys):
            v = item.get(k)
            if v is not None:
                m.update(json.dumps(v, sort_keys=True).encode("utf-8"))
        return m.hexdigest()

    def test_connection(self):
        """
        Test API connectivity and authentication.

        Returns:
            dict: Test results with status and detailed information about accessible endpoints
        """
        self.logger.info("Testing connection to Mimecast API")

        # Check available permissions by testing common endpoints
        accessible_endpoints = []
        forbidden_endpoints = []
        not_found_endpoints = []
        error_endpoints = []

        # Test GET endpoints
        get_endpoints = [
            ("/domain/cloud-gateway/v1/internal-domains", "Internal Domains"),
            ("/user/cloud-gateway/v1/users", "Users"),
            ("/email/cloud-gateway/v1/gateway-details", "Gateway Details"),
            ("/email/cloud-gateway/v1/outbound-ip-addresses", "Outbound IP Addresses"),
        ]

        # Test GET endpoints
        for endpoint, description in get_endpoints:
            url = f"{self.base_url}{endpoint}"
            try:
                response = self.session.get(url)
                if response.status_code == 200:
                    accessible_endpoints.append(description)
                elif response.status_code == 403:
                    forbidden_endpoints.append(description)
                    self.logger.info(
                        f"✗ {description} - forbidden (403): {response.text}"
                    )
                elif response.status_code == 404:
                    not_found_endpoints.append(description)
                    self.logger.info(
                        f"? {description} - not found (404): {response.text}"
                    )
                else:
                    error_endpoints.append(
                        f"{description} (HTTP {response.status_code})"
                    )
                    self.logger.info(f"? {description} - status {response.status_code}")
            except Exception as e:
                error_endpoints.append(f"{description} (Error: {str(e)})")
                self.logger.info(f"✗ {description} - error: {e}")

        # Build detailed diagnostic message for UX
        diagnostic_parts = []

        if accessible_endpoints:
            diagnostic_parts.append(
                f"✓ Accessible APIs: {', '.join(accessible_endpoints)}"
            )

        if forbidden_endpoints:
            diagnostic_parts.append(
                f"✗ Forbidden APIs (need OAuth scopes): {', '.join(forbidden_endpoints)}"
            )

        if not_found_endpoints:
            diagnostic_parts.append(
                f"? Unknown APIs (404): {', '.join(not_found_endpoints)}"
            )

        if error_endpoints:
            diagnostic_parts.append(f"⚠ Error APIs: {', '.join(error_endpoints)}")

        # Prepare detailed results
        results = {
            "oauth_working": True,
            "accessible_endpoints": accessible_endpoints,
            "forbidden_endpoints": forbidden_endpoints,
            "not_found_endpoints": not_found_endpoints,
            "error_endpoints": error_endpoints,
            "diagnostic_details": (
                " | ".join(diagnostic_parts)
                if diagnostic_parts
                else "No API endpoints tested successfully"
            ),
        }

        if accessible_endpoints:
            results["status"] = "success"
            results["message"] = (
                f"Connected successfully with access to: {', '.join(accessible_endpoints)}. "
                f"{results['diagnostic_details']}"
            )
        else:
            # Raise descriptive exception for UX since no endpoints are accessible
            error_msg = (
                "OAuth authentication successful but no API endpoints are accessible. "
                f"{results['diagnostic_details']}."
            )
            self.logger.error(error_msg)
            raise Exception(error_msg)

        self.logger.info("Connection test completed")
        return results

    def get_internal_domains(self):
        """
        Retrieve internal domains from Mimecast API with pagination support.

        Yields:
            dict: Internal domain data with original API response structure
        """
        url = f"{self.base_url}/domain/cloud-gateway/v1/internal-domains"
        running_total = 0
        page_token = None

        while True:
            params = {"pageSize": PAGE_SIZE}
            if page_token is not None:
                params["pageToken"] = page_token

            response = self.session.get(url, params=params)
            response.raise_for_status()

            data = response.json()

            # Get domains from response
            domains = data.get("domains", [])

            # Count valid domains for this page
            page_count = 0
            for domain in domains:
                page_count += 1
                yield domain

            # Update running total and log progress
            new_running_total = running_total + page_count
            self.logger.info(
                f"Got MimecastInternalDomain: {running_total} + {page_count} = {new_running_total}"
            )
            running_total = new_running_total

            # Check if there are more pages
            page_token = data.get("meta", {}).get("nextPage", None)
            if not page_token:
                break

    def get_gateway_details(self):
        """
        Retrieve gateway details from Mimecast API.

        Yields:
            dict: gateway details data with original API response structure
        """
        url = f"{self.base_url}/email/cloud-gateway/v1/gateway-details"

        response = self.session.get(url)
        response.raise_for_status()

        data = response.json()
        # Hash the outbound hostnames value
        outbound_hostnames = data.get("outboundHostnames") or "unknown"
        if outbound_hostnames:
            # Convert to string and hash
            hash_value = hashlib.sha256(str(outbound_hostnames).encode()).hexdigest()
            data["x_id"] = hash_value
        # Normalize: ensure list
        if isinstance(data, dict):
            data = [data]
        elif not isinstance(data, list):
            self.logger.warning("Unexpected gateway details response format")
            return

        self.logger.info(f"Got {len(data)} MimecastGatewayDetail")

        for gateway_detail in data:
            yield gateway_detail

    def get_outbound_ip_addresses(self):
        """
        Retrieve outbound IP addresses from Mimecast API.

        Yields:
            dict: outbound IP addresses data with original API response structure
        """
        url = f"{self.base_url}/email/cloud-gateway/v1/outbound-ip-addresses"

        response = self.session.get(url)
        response.raise_for_status()

        data = response.json()

        # Get outbound IP addresses from response
        outbound_ip_addresses = data.get("outboundIpAddresses", [])

        self.logger.info(f"Got {len(outbound_ip_addresses)} MimecastOutboundIpAddress")

        for outbound_ip_address in outbound_ip_addresses:
            # Raw address is usually "/32" CIDR (a single address)
            # Extract the actual IP (first in range, if there's a wider range, but that shouldn't happen)
            raw = outbound_ip_address.get("outboundIpAddress", "")
            try:
                network = ipaddress.ip_network(raw, strict=False)
                outbound_ip_address["x_ip"] = str(network.network_address)
            except (TypeError, ValueError):
                self.logger.warning(f"Invalid CIDR format for outbound IP address: {raw}")
            yield outbound_ip_address

    def get_threats_by_recipient(self):
        """
        Retrieve threats by recipient from Mimecast API with pagination support.
        """
        url = f"{self.base_url}/threats/v1/stats/threats-by-recipient"
        running_total = 0
        page_token = None
        # Compute timestamp range start (UTC, ISO 8601)
        timestamp_range_starts_at = (
            datetime.now(timezone.utc) - timedelta(days=self.lookback_days)
        ).strftime("%Y-%m-%dT%H:%M:%SZ")

        while True:
            params = {
                "pageSize": PAGE_SIZE,
                "timestampRangeStartsAt": timestamp_range_starts_at,
            }
            if page_token:
                params["pageToken"] = page_token

            response = self.session.get(url, params=params)
            response.raise_for_status()

            data = response.json()
            threats_by_recipient = data.get("value", [])
            for threat in threats_by_recipient:
                # Generate a unique threat ID from the hash of the grouping key values
                hash_id = self.hash(threat, THREAT_PROPERTIES)
                threat["x_id"] = hash_id

            page_count = 0
            for threat in threats_by_recipient:
                page_count += 1
                yield threat

            running_total += page_count
            self.logger.info(
                f"Got MimecastThreatByRecipient: {running_total - page_count} + {page_count} = {running_total}"
            )

            page_token = data.get("meta", {}).get("nextPage")
            if not page_token:
                break

    def get_users(self):
        """
        Retrieve users from Mimecast API with pagination support.

        Yields:
            dict: user data with original API response structure
        """
        url = f"{self.base_url}/user/cloud-gateway/v1/users"
        running_total = 0
        page_token = None

        while True:
            params = {"pageSize": PAGE_SIZE}
            if page_token:
                params["pageToken"] = page_token

            response = self.session.get(url, params=params)
            response.raise_for_status()
            data = response.json()
            # Get users from response
            users = data.get("users", [])
            # Count valid users for this page
            # (Mimecast user list includes all the email recipients... we only want actual "users")
            page_count = 0
            filtered_count = 0
            for user in users:
                page_count += 1
                if user.get("addressType") != "created_by_email":
                    filtered_count += 1
                    yield user

            # Update running total and log progress
            new_running_total = running_total + page_count
            self.logger.info(
                f"Got MimecastUser: {running_total} + {page_count} = {new_running_total} filtered to {filtered_count}"
            )
            running_total = new_running_total

            # Check if there are more pages
            page_token = data.get("meta", {}).get("nextPage", None)
            if not page_token:
                break
