
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class MimecastGatewayDetail(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class MimecastInternalDomain(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class MimecastOutboundIpAddress(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class MimecastThreatByRecipient(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class MimecastUser(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
