
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class CynetEDREnumSeverity(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CynetEDRHost(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CynetEDRMisconfiguration(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CynetEDRMisconfigurationFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CynetEDRUser(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CynetEDRVulnerability(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CynetEDRVulnerabilityFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
