
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class BlueCatMicetroAAAARecord(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BlueCatMicetroARecord(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BlueCatMicetroCNAMERecord(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BlueCatMicetroDevice(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BlueCatMicetroIPAMRecord(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BlueCatMicetroRange(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BlueCatMicetroZone(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
