"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""
# flake8: noqa
from .fn_test import test
from .fn_get_devices import get_devices
from .fn_get_users import get_users
