
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class LansweeperClassicAsset(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class LansweeperClassicSoftware(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class LansweeperClassicSoftwareInstallation(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
