
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class CiscoIntersightAccount(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CiscoIntersightClusterMember(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CiscoIntersightFabricInterconnect(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CiscoIntersightHyperflexCluster(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CiscoIntersightNode(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CiscoIntersightOrganization(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CiscoIntersightPhysicalSummary(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CiscoIntersightTag(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
