
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class Docusnap365Data(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class Docusnap365Hardware(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class Docusnap365IPHost(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class Docusnap365Network(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class Docusnap365Organization(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class Docusnap365Person(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class Docusnap365Platform(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class Docusnap365Site(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class Docusnap365Storage(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class Docusnap365SystemDetails(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class Docusnap365SystemToHardwareRelation(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
