
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""

from typing import Any, Optional, TypedDict  # noqa: F401

Settings = TypedDict('Settings', {
    'url': str,
    'username': str,
    'password': str,
    'look_back_days': int,
    'device_families': list,
    'device_in_use': bool,
    'only_active_device': bool,
    'cve_score': int,
    'anomaly_severity': str,
})
