
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class AsimilyAnomaly(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class AsimilyAnomalyFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class AsimilyDevice(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class AsimilyVulnerability(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class AsimilyVulnerabilityFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class AsimilyVulnerabilitySeverityEnum(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
