
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class BitbucketDCProject(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BitbucketDCRepository(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
