
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class Auth0Client(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class Auth0Organization(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class Auth0Role(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class Auth0User(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
