
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""

from typing import Any, Optional, TypedDict  # noqa: F401

Settings = TypedDict('Settings', {
    'api_key': str,
    'min_risk_severity': str,
    'active_domains_only': bool,
    'import_vendor_assets': bool,
})
