
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class UpGuardDomain(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class UpGuardExposureCategoryEnum(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class UpGuardExposureSeverityEnum(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class UpGuardIpAddress(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class UpGuardRisk(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class UpGuardRiskFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class UpGuardVendor(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class UpGuardVendorQuestionnaire(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class UpGuardVulnerability(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class UpGuardVulnerabilityFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
