
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""

from typing import Any, Optional, TypedDict  # noqa: F401

Settings = TypedDict('Settings', {
    'url': str,
    'tenant': str,
    'client_id': str,
    'client_secret': str,
    'refresh_token': str,
    'active_workers': bool,
    'termination_date_fieldname': Optional[str],
})
