
QUALYS_API_TIMEOUT_SECS = 600
QUALYS_API_GET_STATUS_SLEEP_SECS = 10
MAX_RATE_LIMIT_RETRIES = 3

QUALYS_VULN_STATES_MAP = {
    "NEW": "New",
    "ACTIVE": "Active",
    "REOPENED": "Re-Opened",
    "FIXED": "Fixed"
}

QUALYS_DEFAULT_VULN_STATES = ["NEW", "ACTIVE", "REOPENED"]

QUALYS_DEFAULT_SEVERITY = 4

REPORT_STATE_SUBMITTED = "SUBMITTED"
REPORT_STATE_RUNNING = "RUNNING"
REPORT_STATE_FINISHED = "FINISHED"
REPORT_STATE_CANCELED = "CANCELED"

HOST_DETECTION_BATCH_SIZE = 1000
KBASE_BATCH_SIZE = 1000

DETECTION_BOOL_FIELDS = [
    "SSL",
    "IS_IGNORED",
    "IS_DISABLED",
    "PATCHABLE",
]
