
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""

from typing import Any, Optional, TypedDict  # noqa: F401

Settings = TypedDict('Settings', {
    'api_url': str,
    'username': str,
    'password': str,
    'min_severity': int,
    'asset_groups': str,
    'asset_group_batch_size': int,
    'asset_tag': str,
    'del_reports': bool,
    'cancel_running_reports': bool,
    'use_default_template': bool,
    'vuln_states': list,
})
