
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class QualysEnumSeverity(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class QualysFinding2(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class QualysHost2(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class QualysQID(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class QualysQidDetail2(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
