
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class EzoAssetSonarAsset(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class EzoAssetSonarGroup(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class EzoAssetSonarLocation(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class EzoAssetSonarMember(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class EzoAssetSonarSubGroup(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
