
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class HalcyonAsset(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class HalcyonDeploymentGroup(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class HalcyonPolicyGroup(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class HalcyonTenant(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
