
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class ScaleComputingFleetManagerCluster(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ScaleComputingFleetManagerEnumOnlineStatus(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ScaleComputingFleetManagerSourceTag(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ScaleComputingFleetManagerVM(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
