
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class VeeamDataPlatformBackupJob(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class VeeamDataPlatformInventory(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class VeeamDataPlatformJob(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class VeeamDataPlatformManagedServer(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class VeeamDataPlatformRepository(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class VeeamDataPlatformRestorePoint(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
