
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class KeycloakClient(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class KeycloakGroup(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class KeycloakRealm(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class KeycloakUser(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
