
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class AppCheckDastDomain(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class AppCheckDastExposure(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class AppCheckDastExposureSeverityEnum(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class AppCheckDastFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class AppCheckDastScan(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
