
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class NudgeSecurityAccount(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NudgeSecurityApp(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NudgeSecurityExposure(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NudgeSecurityFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NudgeSecurityUser(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NudgeSecurityUserGroup(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
