
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class HclAppscanApplication(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class HclAppscanEnumExposureType(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class HclAppscanExposure(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class HclAppscanFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class HclAppscanScan(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
