
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class SolarWindsOrionAgent(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SolarWindsOrionApplication(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SolarWindsOrionApplicationTemplate(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SolarWindsOrionNode(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
