
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class AnthropicClaudeCodeUser(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class AnthropicUser(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class AnthropicWorkspace(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
