
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""

from typing import Any, Optional, TypedDict

Settings = TypedDict('Settings', {
    'url': str,
    'api_key': str,
    'verify_tls': bool,
    'page_limit': int,
    'total_pages': Optional[int],
})
