
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class SnowAtlasComputer(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SnowAtlasMobileDevice(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SnowAtlasOperationalStatusEnum(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SnowAtlasOrganization(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SnowAtlasUser(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
