
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class VeracodeApplication(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class VeracodeDynamicExposure(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class VeracodeDynamicFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class VeracodeStaticExposure(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class VeracodeStaticFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class VeracodeTeam(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class VeracodeWebsite(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
