
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class JFrogArtifactoryEnumEnvironment(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class JFrogArtifactoryProject(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class JFrogArtifactoryRepository(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class JFrogArtifactoryUser(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class JFrogArtifactoryUserGroup(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
