
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class CyCognitoCertificate(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CyCognitoDomain(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CyCognitoExposure(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CyCognitoFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CyCognitoIpAddress(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CyCognitoIpRange(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class CyCognitoWebApp(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
