
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class BeyondTrustBeyondInsightAsset(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BeyondTrustBeyondInsightCloud(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BeyondTrustBeyondInsightDatabase(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BeyondTrustBeyondInsightDirectory(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BeyondTrustBeyondInsightFunctionalAccount(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BeyondTrustBeyondInsightManagedAccount(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BeyondTrustBeyondInsightOrganization(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BeyondTrustBeyondInsightPlatform(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BeyondTrustBeyondInsightUser(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BeyondTrustBeyondInsightUserGroup(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class BeyondTrustBeyondInsightWorkgroup(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
