
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class ForgeRockApplication(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ForgeRockGroup(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ForgeRockOrganization(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ForgeRockRole(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ForgeRockUser(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
