
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class ZimperiumMTDApp(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ZimperiumMTDDevice(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ZimperiumMTDExposureSeverityEnum(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ZimperiumMTDOSFamilyEnum(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ZimperiumMTDScanApp(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ZimperiumMTDScanAppExposure(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ZimperiumMTDScanAppFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ZimperiumMTDSoftwareInstallation(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ZimperiumMTDTeam(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ZimperiumMTDThreat(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ZimperiumMTDVulnerability(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class ZimperiumMTDVulnerabilityFinding(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
