
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class SymmetryDataGuardClassificationEnum(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SymmetryDataGuardClassifiedObject(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SymmetryDataGuardCloudProviderEnum(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SymmetryDataGuardIdentity(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SymmetryDataGuardObjectXref(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SymmetryDataGuardStorage(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class SymmetryDataGuardStoreXref(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
