
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""

from typing import Any, Optional, TypedDict  # noqa: F401

Settings = TypedDict('Settings', {
    'ca_server': str,
    'ca_name': str,
    'username': str,
    'password': str,
    'verify_tls': bool,
})
