
"""
DO NOT EDIT THIS FILE

This file is generated from the connector.spec.yaml file, using codegen:

    $ surcom connector codegen
"""


class NutanixPrismCentralCluster(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NutanixPrismCentralEnumOperationalStatus(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NutanixPrismCentralHost(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NutanixPrismCentralImage(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NutanixPrismCentralSubnet(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NutanixPrismCentralVirtualMachine(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)


class NutanixPrismCentralVpc(dict):
    def __init__(self, content: dict):
        super().__init__(type=self.__class__.__name__, content=content)
